import { KYC_URL } from "../../constants";
import { apiSlice } from "./apiSlice";

export const kycApiSlice = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    // Mutation for creating/updating KYC data
    kyc: builder.mutation({
      query: (creds) => ({
        url: `${KYC_URL}`,
        method: "POST",
        body: creds,
      }),
    }),
    // Query for fetching KYC data by ID
    getKycData: builder.query({
      query: (id) => ({
        url: `${KYC_URL}/${id}`,
        method: "GET",
      }),
    }),
  }),
});

// Export hooks generated by RTK Query
export const { useKycMutation, useGetKycDataQuery } = kycApiSlice;
